### ISSUE TITLE
Integrate other package managers

### ISSUE THREAD

**Issue by eathtespagheti** [astavares/bashflix#12]
I think other package managers such as `pacman`, `yay` and `dnf` should be integrated in the installer, to make the install process smooth on non apt linux distros

I've written a basic solution for installing on diffrent OSes with diffrent package managers, you can check it [here](https://github.com/eathtespagheti/bash-things/blob/master/firstrun/firstrun-arch.sh), if you like it I can try to implement my custom installer in yours

**Comment by astavares** [comment]
hello. I have already a solution that I will merge to master soon
https://github.com/astavares/bashflix/blob/dev/install.sh

**Comment by eathtespagheti** [comment]
Cool! Keep up with the good work then!
